# gui_language.py

LANG_JA = "ja"
LANG_EN = "en"

# ---------------------------
# UI strings
# ---------------------------
UI_TEXT = {
    "ja": {
        "language": "Language:",
        "all": "すべて",
        "type_filter": "タイプフィルタ",
        "camera_mode": "カメラモード",
        "reset": "プレイヤー / ライフ リセット",
        "generate_fm_txt": "デッキ(txt)から画像生成",
        "load_csv": "CSVを読み込む",
        "commander": "統率者",
        "commander_a": "統率者A表示",
        "commander_b": "統率者B表示",
        "label_commander_a": "統率者A",
        "label_commander_b": "統率者B",
        "companion": "相棒表示",
        "text_size": "カード テキストサイズ",
        "flip_back": "裏面",
        "flip_front": "表面",
        "player": "プレイヤー",
        "life": "ライフ",
        "set_commander_a": "統率者Aに設定",
        "set_commander_b": "統率者Bに設定",
        "set_companion": "相棒に設定",
        "unset_commander_a": "統率者Aを解除",
        "unset_commander_b": "統率者Bを解除",
        "unset_companion": "相棒を解除",
        "select_image": "カード画像選択",
        "commander_counters": "統率者ダメージ / カウンター",
        "commander_damage": "統率者ダメージ",
        "commander_counters_placeholder":
            "・統率者ダメージ\n"
            "・毒カウンター\n"
            "・経験カウンター\n\n"
            "（後で実装予定）",
        "mulligan": "マリガン",
        "keep": "キープ",
        "start": "スタート",
        "select_csv": "デッキ CSV を選択",
        "mulligan_status": "現在のマリガン:",
        "free_mulligan": "フリーマリガン",
        "initial_hand": "初手",
        "bottom_required": "戻す枚数:",
        "need_select_bottom": "{n} 枚のカードを選択してください。",
        "kept": "キープしました。",
        "rating": "評価:",
        "average_hand_size": "平均ハンド枚数:",
        "runs": "実行回数:",
        "most_bottomed_cards": "よくボトムに戻されるカード:",
        "most_kept_cards": "よくキープされるカード:",
        "start_simulation": "シミュレーション開始",
        "recent_results": "評価別の最近の結果 (最大5件):",
        "rating_header_prefix": "評価",
        "reset_results": "結果をリセット",
        "reset_confirm_title": "リセットの確認",
        "reset_confirm_msg": "このデッキのすべてのシミュレーション結果を削除してもよろしいですか？",
        "btn_serum_powder": "血清の粉末を起動",
        "exiled_cards_label": "追放したカード：",
        "mulligan_simulator": "マリガンシミュレーターを起動",
        "csv_not_loaded": "先にCSVを読み込んでください",
        "event_log": "イベントログ",
        "log_damage_inc": "Player {p}の統率者{c}から {d}点ダメージ",
        "log_damage_dec": "Player {p}の統率者{c}からのダメージ{d}点を訂正",
        "log_life_inc": "ライフ{n}点回復",
        "log_life_dec": "ライフ{n}点失う",
        "log_counter_inc": "{name}カウンタ {n}個増加",
        "log_counter_dec": "{name}カウンタ {n}個減少",
        "time_min_ago": "{n}分前",
        "time_sec_ago": "{n}秒前",
        "deck_building": "構築モードを起動",
        "mainboard": "メインボード",
        "creature": "クリーチャー",
        "spell": "呪文 (土地/クリーチャー以外)",
        "land": "土地",
        "considering": "検討中",
        "add": "追加",
        "search_card_placeholder": "カード名を入力...",
        "destination": "追加先",
        "search_adding": "取得中...",
        "card_not_found": "カードが見つかりません",
        "export_txt": "txtに出力",
        "move_to_considering": "検討中に移動",
        "move_to_mainboard": "メインに移動",
        "delete_card": "カード削除",
        "confirm_delete": "このカードを削除しますか？",
        "add_different_illustration": "別のイラストのカードを追加する",
        "tokens": "トークン",
        "sync_tokens": "トークンリスト生成",
        "generate_token_list": "トークンリスト生成",
        "launch_test_play": "TestPlayモードを起動",
        "reset_game": "ゲームをリセット",
        "next_turn": "次のターン",
        "draw_7": "7枚引く",
        "draw_x": "X枚引く",
        "draw_bottom": "ボトムのカードを引く",
        "undo": "元に戻す",
        "redo": "やり直し",
        "discard_hand": "ハンドをすべて捨てる",
        "discard_random": "ランダムに1枚捨てる",
        "put_on_top": "デッキのTopに置く",
        "put_on_bottom": "デッキのBottomに置く",
        "add_counter": "カウンターを乗せる",
        "loyalty": "忠誠度",
        "lore_counter": "伝承",
        "flip_face_down": "裏向きにする",
        "flip_face_up": "表向きにする",
        "toggle_no_untap": "アンタップ制限切り替え",
        "exile_all_graveyard": "すべて追放する",
        "return_all_to_library": "すべてライブラリに戻す",
        "delete_token": "削除する",
        "log_tapped": "{name}をタップしました",
        "log_untapped": "{name}をアンタップしました",
        "log_drew": "{name}をドローしました",
        "log_moved": "{name}を{src}から{dst}へ移動しました",
        "log_token_generated": "{name}を{dst}に生成しました",
        "log_shuffled": "ライブラリを切り直しました",
        "log_added_counter": "{name}に{label}カウンターを{n}個乗せました (合計: {total})",
        "log_annihilated": "{name}の+1/+1カウンターと-1/-1カウンターが相殺されました",
        "log_mulligan": "マリガン：{n}枚キープ",
        "log_turn": "************* ターン {n} **************",
        "log_reset": "ゲームをリセットしました",
        "toggle_log": "ログ表示切替",
        "always_show_top": "常に一番上を表示",
        "view_library": "ライブラリを見る",
        "shuffle_library": "ライブラリを切り直す",
        "view_graveyard": "墓地を見る",
        "view_exile": "追放領域を見る",
        "life_label_scene": "ライフ",
        "turn": "ターン",
        "test_play_title": "テストプレイ",
        "close": "閉じる",
        "zone_hand": "手札",
        "zone_library": "ライブラリ",
        "zone_graveyard": "墓地",
        "zone_exile": "追放領域",
        "zone_command": "統率者領域",
        "zone_battlefield": "戦場",
        "zone_lands": "土地領域",
    },
    "en": {
        "language": "Language:",
        "all": "All",
        "type_filter": "Type Filter",
        "camera_mode": "Camera Mode",
        "reset": "Player / Life Reset",
        "generate_fm_txt": "Generate from Deck (txt)",
        "load_csv": "Load CSV",
        "commander": "Commander",
        "commander_a": "Show Commander A",
        "commander_b": "Show Commander B",
        "label_commander_a": "Commander A",
        "label_commander_b": "Commander B",
        "companion": "Show Companion",
        "text_size": "Card Text Size",
        "flip_back": "Back",
        "flip_front": "Front",
        "player": "Player",
        "life": "Life",
        "set_commander_a": "Set as Commander A",
        "set_commander_b": "Set as Commander B",
        "set_companion": "Set as Companion",
        "unset_commander_a": "Unset Commander A",
        "unset_commander_b": "Unset Commander B",
        "unset_companion": "Unset Companion",
        "select_image": "Select Card Image",
        "commander_counters": "Commander Damage / Counters",
        "commander_damage": "Commander Damage",
        "commander_counters_placeholder":
            "• Commander Damage\n"
            "• Poison Counters\n"
            "• Experience Counters\n\n"
            "(Coming soon)",
        "mulligan": "Mulligan",
        "keep": "Keep",
        "start": "Start",
        "select_csv": "Select Deck CSV",
        "mulligan_status": "Current Mulligan:",
        "free_mulligan": "Free Mulligan",
        "initial_hand": "Initial Hand",
        "bottom_required": "Cards to bottom:",
        "need_select_bottom": "Select {n} cards to bottom.",
        "kept": "Hand kept.",
        "rating": "Rating:",
        "average_hand_size": "Average Hand Size:",
        "runs": "Runs:",
        "most_bottomed_cards": "Most Bottomed Cards:",
        "most_kept_cards": "Most Kept Cards:",
        "start_simulation": "Start Simulation",
        "recent_results": "Recent Results by Rating (Max 5):",
        "rating_header_prefix": "Rating",
        "reset_results": "Reset Results",
        "reset_confirm_title": "Confirm Reset",
        "reset_confirm_msg": "Are you sure you want to delete all simulation results for this deck?",
        "btn_serum_powder": "Activate Serum Powder",
        "exiled_cards_label": "Exiled Cards:",
        "mulligan_simulator": "Launch Mulligan Simulator",
        "csv_not_loaded": "Please load a CSV first",
        "event_log": "Event Log",
        "log_damage_inc": "{d} damage from Player {p}'s Commander {c}",
        "log_damage_dec": "Corrected {d} damage from Player {p}'s Commander {c}",
        "log_life_inc": "Gained {n} life",
        "log_life_dec": "Lost {n} life",
        "log_counter_inc": "{name} counter increased by {n}",
        "log_counter_dec": "{name} counter decreased by {n}",
        "time_min_ago": "{n} min ago",
        "time_sec_ago": "{n} sec ago",
        "deck_building": "Launch Deck Building Mode",
        "mainboard": "Mainboard",
        "creature": "Creature",
        "spell": "Spell (non-land/creature)",
        "land": "Land",
        "considering": "Considering",
        "add": "Add",
        "search_card_placeholder": "Enter card name (EN)...",
        "destination": "To",
        "search_adding": "Fetching...",
        "card_not_found": "Card not found",
        "export_txt": "Export to txt",
        "move_to_considering": "Move to Considering",
        "move_to_mainboard": "Move to Main",
        "delete_card": "Delete Card",
        "confirm_delete": "Delete this card?",
        "add_different_illustration": "Add card with different illustration",
        "tokens": "Tokens",
        "sync_tokens": "Generate Token List",
        "generate_token_list": "Generate Token List",
        "launch_test_play": "Launch TestPlay Mode",
        "reset_game": "Reset Game",
        "next_turn": "Next Turn",
        "draw_7": "Draw 7",
        "draw_x": "Draw X",
        "draw_bottom": "Draw from bottom",
        "undo": "Undo",
        "redo": "Redo",
        "discard_hand": "Discard all cards in hand",
        "discard_random": "Discard a card at random",
        "put_on_top": "Put on top of library",
        "put_on_bottom": "Put on bottom of library",
        "add_counter": "Add counter",
        "loyalty": "Loyalty",
        "lore_counter": "Lore",
        "flip_face_down": "Flip face-down",
        "flip_face_up": "Turn face-up",
        "toggle_no_untap": "Toggle 'Does not untap'",
        "exile_all_graveyard": "Exile all",
        "return_all_to_library": "Return all to library",
        "delete_token": "Delete",
        "log_tapped": "Tapped {name}",
        "log_untapped": "Untapped {name}",
        "log_drew": "Drew {name}",
        "log_moved": "Moved {name} from {src} to {dst}",
        "log_token_generated": "Generated {name} in {dst}",
        "log_shuffled": "Library shuffled.",
        "log_added_counter": "Added {n} {label} counter(s) to {name} (Total: {total})",
        "log_annihilated": "+1/+1 and -1/-1 counters canceled out on {name}",
        "log_mulligan": "Mulligan: Kept {n} cards",
        "log_turn": "************* Turn {n} **************",
        "log_reset": "Game reset.",
        "toggle_log": "Toggle Log",
        "always_show_top": "Always Show Top",
        "view_library": "View Library",
        "shuffle_library": "Shuffle Library",
        "view_graveyard": "View Graveyard",
        "view_exile": "View Exile",
        "life_label_scene": "LIFE",
        "turn": "Turn",
        "test_play_title": "Test Play",
        "close": "Close",
        "zone_hand": "Hand",
        "zone_library": "Library",
        "zone_graveyard": "Graveyard",
        "zone_exile": "Exile",
        "zone_command": "Command",
        "zone_battlefield": "Battlefield",
        "zone_lands": "Lands",
    }
}


# ---------------------------
# Card type display
# Internal values (English) → Display names
# ---------------------------
TYPE_LABELS = {
    "ja": {
        "Land": "土地",
        "Creature": "クリーチャー",
        "Enchantment": "エンチャント",
        "Artifact": "アーティファクト",
        "Instant": "インスタント",
        "Sorcery": "ソーサリー",
        "Kindred": "同族",
        "Planeswalker": "プレインズウォーカー",
        "Battle": "バトル",
    },
    "en": {
        "Land": "Land",
        "Creature": "Creature",
        "Enchantment": "Enchantment",
        "Artifact": "Artifact",
        "Instant": "Instant",
        "Sorcery": "Sorcery",
        "Kindred": "Kindred",
        "Planeswalker": "Planeswalker",
        "Battle": "Battle",
    }
}
